theme = "doom_acario_dark"

[editor]
mouse = false
auto-completion = false
auto-format = false
line-number = "relative"
indent-heuristic = "simple"
rulers = [128, 256]
text-width = 128
trim-trailing-whitespace = true
trim-final-newlines = true
insert-final-newline = true
scrolloff = 0
scroll-lines = 8
auto-pairs = false

[editor.smart-tab]
enable = false
supersede-menu = false

[keys.normal]
tab = "normal_mode"
S-tab = "insert_tab"
esc = "no_op"

[keys.insert]
tab = "normal_mode"
S-tab = "insert_tab"
esc = "no_op"

[keys.select]
tab = "normal_mode"
S-tab = "insert_tab"
esc = "no_op"
